server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: route1
          uri: http://localhost:8081/hello-world
          predicates:
            - Path=/**
          filters:
            - name: CustomRateLimitFilter