server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: route1
          uri: http://localhost:8081/hello-world
          predicates:
            - Path=/**
          filters:
            - name: RequestRateLimiter
              args:
                rate-limiter: "#{@defaultGatewayRateLimiter}"
                key-resolver: "#{@defaultGatewayKeyResolver}"
                deny-empty-key: false
                status-code: TOO_MANY_REQUESTS
                default-gateway-rate-limiter.requestedToken: 1